const FONT_SIZES_TYPE = {
  XXS: 'xxs',
  XS: 'xs',
  SM: 'sm',
  MD: 'md',
  LG: 'lg',
  XL: 'xl',
  XXL: 'xxl',
} as const;

const FONT_SIZES = {
  [FONT_SIZES_TYPE.XXS]: 14,
  [FONT_SIZES_TYPE.XS]: 16,
  [FONT_SIZES_TYPE.SM]: 18,
  [FONT_SIZES_TYPE.MD]: 20,
  [FONT_SIZES_TYPE.LG]: 22,
  [FONT_SIZES_TYPE.XL]: 24,
  [FONT_SIZES_TYPE.XXL]: 26,
} as const;

const FONT_WEIGHTS_TYPE = {
  REGULAR: 'regular',
  MEDIUM: 'medium',
  BOLD: 'bold',
} as const;

const FONT_WEIGHTS = {
  [FONT_WEIGHTS_TYPE.REGULAR]: 400,
  [FONT_WEIGHTS_TYPE.MEDIUM]: 500,
  [FONT_WEIGHTS_TYPE.BOLD]: 700,
} as const;

const COLORS_TYPE = {
  GREY_001: 'grey001',
  GREY_002: 'grey002',
  GREY_003: 'grey003',
  GREY_004: 'grey004',
  GREY_005: 'grey005',
  WHITE_GREY_001: 'white_grey001',
  WHITE_GREY_002: 'white_grey002',
  BLACK_001: 'black001',
  RED_001: 'red001',
};

const COLORS = {
  [COLORS_TYPE.GREY_001]: '#D5D3D1',
  [COLORS_TYPE.GREY_002]: '#ABA7A3',
  [COLORS_TYPE.GREY_003]: '#817A75',
  [COLORS_TYPE.GREY_004]: '#615A52',
  [COLORS_TYPE.GREY_005]: '#4C433B',
  [COLORS_TYPE.WHITE_GREY_001]: '#EEEEEE',
  [COLORS_TYPE.WHITE_GREY_002]: '#D1D1D1',
  [COLORS_TYPE.BLACK_001]: '#2D2218',
  [COLORS_TYPE.RED_001]: '#FF0000',
} as const;

const Z_INDEX_LAYER_TYPE = {
  LEVEL_1: 'level1',
  LEVEL_2: 'level2',
  LEVEL_3: 'level3',
  LEVEL_4: 'level4',
  LEVEL_5: 'level5',
  LEVEL_6: 'level6',
  LEVEL_7: 'level7',
  LEVEL_8: 'level8',
  LEVEL_9: 'level9',
  LEVEL_10: 'level10',
} as const;

const Z_INDEX_LAYER = {
  [Z_INDEX_LAYER_TYPE.LEVEL_1]: -10000,
  [Z_INDEX_LAYER_TYPE.LEVEL_2]: 0,
  [Z_INDEX_LAYER_TYPE.LEVEL_3]: 1,
  [Z_INDEX_LAYER_TYPE.LEVEL_4]: 10,
  [Z_INDEX_LAYER_TYPE.LEVEL_5]: 25,
  [Z_INDEX_LAYER_TYPE.LEVEL_6]: 50,
  [Z_INDEX_LAYER_TYPE.LEVEL_7]: 100,
  [Z_INDEX_LAYER_TYPE.LEVEL_8]: 2500,
  [Z_INDEX_LAYER_TYPE.LEVEL_9]: 5000,
  [Z_INDEX_LAYER_TYPE.LEVEL_10]: 10000,
} as const;

export {
  FONT_SIZES_TYPE,
  FONT_SIZES,
  FONT_WEIGHTS_TYPE,
  FONT_WEIGHTS,
  COLORS_TYPE,
  COLORS,
  Z_INDEX_LAYER_TYPE,
  Z_INDEX_LAYER,
};
